Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kio' : '@same'
    'frameworks/kxmlgui' : '@same'
    'frameworks/ktextwidgets' : '@same'
    'frameworks/knotifications' : '@same'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows/Qt5' ]
  cppcheck-ignore-files: ['templates/']
